{{- $logoFileName :=  printf "logo.%s" (tpl (.Values.app.logoFileExtension | toString) .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
  labels:
    app: landing-page
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/landing-page-config-map.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: landing-page-container
          image: {{ tpl (.Values.landingPage.image | toString) . }}
          imagePullPolicy: {{ if .Values.landingPage.imagePullPolicy }}{{ tpl (.Values.landingPage.imagePullPolicy | toString) . }}{{ else }}{{ tpl (.Values.imagePullPolicy | toString) . }}{{ end }}
          ports:
            - name: http
              containerPort: 4173
              protocol: TCP
          volumeMounts:
            - name: landing-page-config
              mountPath: /app/landing-page/public/config.js
              subPath: config.js
      {{- if .Values.landingPage.imagePullSecret }}
      imagePullSecrets:
        - name: {{ tpl (.Values.landingPage.imagePullSecret | toString) . }}
      {{- end }}
      volumes:
        - name: landing-page-config
          configMap:
            name: landing-page-config
---
apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  labels:
    app: landing-page
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
    - name: http
      protocol: TCP
      port: 4173
      targetPort: 4173
