{{- $ingressName := .Values.ingress.instanceName | default "default-ingress-name" | toString }}
{{- $monitor := .Values.demoApplication.monitor | default "true" | toString }}
{{- $tracker := .Values.demoApplication.activityTracker | default "false" | toString }}

{{- range .Values.appDefinitions }}
---
apiVersion: theia.cloud/v1beta9
kind: AppDefinition
metadata:
  name: {{ .name | toString }}
spec:
  name: {{ .name | toString }}
  image: {{ .image | toString }}
  pullSecret: {{ .pullSecret | toString  }}
  uid: 0
  port: {{ .port | toString }}
  ingressname: {{ $ingressName }}
  minInstances: 0
  maxInstances: 10
  timeout: {{ .timeout | toString  }}
  requestsMemory: {{ .requestsMemory | toString  }}
  limitsMemory: {{ .limitsMemory | toString }}
  requestsCpu: {{ .requestsCpu | toString  }}
  limitsCpu: {{ .limitsCpu | toString  }}
  downlinkLimit: 30000
  uplinkLimit: 30000
  mountPath: {{ .mountPath| toString  }}
{{- end }}
