apiVersion: v1
kind: Service
metadata:
  name: conversion-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tls
      port: 443
      targetPort: 8443
  selector:
    app: conversion-webhook
  type: ClusterIP
