apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.conversion.certificateName }}
  namespace: {{ .Release.Namespace }}
spec:
  commonName: crd.conversion.cert
  secretName: {{ .Values.conversion.secretName }}
  dnsNames:
    - "crd-conversion-webhook.theiacloud.svc"
  issuerRef:
    name: theia-cloud-selfsigned-issuer
    kind: ClusterIssuer
