apiVersion: v1
kind: Service
metadata:
  name: crd-conversion-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: tls
      port: 443
      targetPort: 8443
  selector:
    app: crd-conversion-webhook
  type: ClusterIP
